import "./globals.css";
import Head from "next/head";
export const metadata = {
  title: "Sensei inu",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      url: "/fav.png",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
