import "./globals.css";

export const metadata = {
  title: "Sensei inu",
  description: "Generated by create next app",
  icons: {
    rel: "icon",
    type: "image/png",
    icon: "/icons/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
